name: apuntar-api
services:
#  apuntar-app:
#    build: .
#    container_name: apuntar-backend
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://sql_db:5432/apuntar-pg
#      - SPRING_MONGODB_URI=mongodb://root:rootroot@nsql_db:27017/apuntar-mongo?authSource=admin
#      - TZ=America/Argentina/Buenos_Aires
#    depends_on:
#      sql_db:
#        condition: service_healthy
#      nsql_db:
#        condition: service_healthy

  sql_db:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=apuntar-pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Argentina/Buenos_Aires
      - PGTZ=America/Argentina/Buenos_Aires
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d apuntar-pg" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql
    restart: unless-stopped

  nsql_db:
   image: mongo:8.2.7
   container_name: apuntar-mongo
   environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=rootroot
   ports:
    - "27017:27017"
   volumes:
     - mongo_data:/data/db
   restart: unless-stopped
   healthcheck:
     test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
     interval: 5s
     timeout: 5s
     retries: 3

volumes:
  pg_data:
    name: apuntar-postgres
  mongo_data:
    name: apuntar-mongo

