name: apuntar-api
services:
  sql_db:
    image: postgres:18
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=apuntar-pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d apuntar-pg" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql
    restart: unless-stopped

  nsql_db:
   image: mongo:8.2.7
   container_name: apuntar-mongo
   environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=rootroot
   ports:
    - "27017:27017"
   volumes:
     - mongo_data:/data/db
   restart: unless-stopped
   healthcheck:
     test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
     interval: 5s
     timeout: 5s
     retries: 3

volumes:
  pg_data:
    name: apuntar-postgres
  mongo_data:
    name: apuntar-mongo

