up:
	docker compose up -d

logs-sql:
	docker compose logs -f sql_db

logs-nsql:
	docker compose logs -f nsql_db

down:
	docker compose down

clean: #para limpiar todos los volumenes si se rompio algo :(
	docker compose down -v