spring.application.name=apuntar
management.endpoints.web.exposure.include=health,info,env,metrics
management.endpoint.health.show-details=always

#properties inexistentes
spring.jackson.deserialization.fail-on-unknown-properties=true
#no serializar null
spring.jackson.default-property-inclusion=non_null

#postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/apuntar-pg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#mongo
spring.mongodb.uri=mongodb://root:rootroot@localhost:27017/apuntar-mongo?authSource=admin

# Límite de tamaño de archivo para uploads (20MB)
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB

# Configuración para usar Jackson como el convertidor JSON preferido
spring.mvc.converters.preferred-json-mapper=jackson